CSG8_TEMPLATES = {}
CSG8_TEMPLATES.__index = CSG8_TEMPLATES

CSG8_TEMPLATES.vehicleTemplates= {
  [1] = {
    ["name"] = "Tank Platoon Entrenched T-72 NE 1",
    ["statics"] = {
      [1] = {
        name = "T-72B",
        offsetX = 0,
        offsetY = 0,
        orientation = 315,
        category = "Ground Vehicles",
      },
      [2] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = 0,
        offsetY = 0,
        orientation = 45,
        category = "Fortification",
      },
      [3] = {
        name = "T-72B",
        offsetX = -67,
        offsetY = -28,
        orientation = 315,
        category = "Ground Vehicles",
      },
      [4] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -67,
        offsetY = -28,
        orientation = 45,
        category = "Fortification",
      },
      [5] = {
        name = "T-72B",
        offsetX = -128,
        offsetY = -46,
        orientation = 315,
        category = "Ground Vehicles",
      },
      [6] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -128,
        offsetY = -46,
        orientation = 45,
        category = "Fortification",
      },
      [7] = {
        name = "T-72B",
        offsetX = -193,
        offsetY = -23,
        orientation = 315,
        category = "Ground Vehicles",
      },
      [8] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -193,
        offsetY = -23,
        orientation = 45,
        category = "Fortification",
      },
    },
  },
  [2] = {
    ["name"] = "Tank Platoon Entrenched T-72 E 1",
    ["statics"] = {
      [1] = {
        name = "T-72B",
        offsetX = 0,
        offsetY = 0,
        orientation = 270,
        category = "Ground Vehicles",
      },
      [2] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = 0,
        offsetY = 0,
        orientation = 0,
        category = "Fortification",
      },
      [3] = {
        name = "T-72B",
        offsetX = -67,
        offsetY = -28,
        orientation = 270,
        category = "Ground Vehicles",
      },
      [4] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -67,
        offsetY = -28,
        orientation = 0,
        category = "Fortification",
      },
      [5] = {
        name = "T-72B",
        offsetX = -128,
        offsetY = -46,
        orientation = 270,
        category = "Ground Vehicles",
      },
      [6] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -128,
        offsetY = -46,
        orientation = 0,
        category = "Fortification",
      },
      [7] = {
        name = "T-72B",
        offsetX = -193,
        offsetY = -23,
        orientation = 270,
        category = "Ground Vehicles",
      },
      [8] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -193,
        offsetY = -23,
        orientation = 0,
        category = "Fortification",
      },
    },
  },
  [3] = {
    ["name"] = "Tank Platoon Entrenched T-72 SE 1",
    ["statics"] = {
      [1] = {
        name = "T-72B",
        offsetX = 0,
        offsetY = 0,
        orientation = 225,
        category = "Ground Vehicles",
      },
      [2] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = 0,
        offsetY = 0,
        orientation = 315,
        category = "Fortification",
      },
      [3] = {
        name = "T-72B",
        offsetX = -67,
        offsetY = -28,
        orientation = 225,
        category = "Ground Vehicles",
      },
      [4] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -67,
        offsetY = -28,
        orientation = 315,
        category = "Fortification",
      },
      [5] = {
        name = "T-72B",
        offsetX = -128,
        offsetY = -46,
        orientation = 225,
        category = "Ground Vehicles",
      },
      [6] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -128,
        offsetY = -46,
        orientation = 315,
        category = "Fortification",
      },
      [7] = {
        name = "T-72B",
        offsetX = -193,
        offsetY = -23,
        orientation = 225,
        category = "Ground Vehicles",
      },
      [8] = {
        name = "Tac_Revet_50x50x6_Sand_1",
        offsetX = -193,
        offsetY = -23,
        orientation = 315,
        category = "Fortification",
      },
    },
  },
}

CSG8_TEMPLATES.fobTemplates= {
  [1] = {
    ["name"] = "Tents & Trucks 1",
    ["statics"] = {
      [1] = {
        name = "GeneratorF",
        offsetX = 0,
        offsetY = 0,
        orientation = 90,
        category = "Fortification",
      },
      [2] = {
        name = "FARP Tent",
        offsetX = 2,
        offsetY = 12,
        orientation = 0,
        category = "Fortification",
      },
      [3] = {
        name = "FARP Tent",
        offsetX = 20,
        offsetY = 12,
        orientation = 0,
        category = "Fortification",
      },
      [4] = {
        name = "FARP Tent",
        offsetX = 20,
        offsetY = 23,
        orientation = 0,
        category = "Fortification",
      },
      [5] = {
        name = "FARP Tent",
        offsetX = 2,
        offsetY = 23,
        orientation = 0,
        category = "Fortification",
      },
      [6] = {
        name = "FARP Tent",
        offsetX = 2,
        offsetY = 34,
        orientation = 0,
        category = "Fortification",
      },
      [7] = {
        name = "FARP Tent",
        offsetX = 20,
        offsetY = 34,
        orientation = 0,
        category = "Fortification",
      },
      [8] = {
        name = "FARP Tent",
        offsetX = 2,
        offsetY = 46,
        orientation = 0,
        category = "Fortification",
      },
      [9] = {
        name = "FARP Tent",
        offsetX = 20,
        offsetY = 46,
        orientation = 0,
        category = "Fortification",
      },
      [10] = {
        name = "GAZ-66",
        offsetX = 23,
        offsetY = 58,
        orientation = 90,
        category = "Ground Vehicles",
      },
      [11] = {
        name = "GAZ-66",
        offsetX = 19,
        offsetY = 58,
        orientation = 90,
        category = "Ground Vehicles",
      },
      [12] = {
        name = "GAZ-66",
        offsetX = 15,
        offsetY = 58,
        orientation = 90,
        category = "Ground Vehicles",
      },
      [13] = {
        name = "GAZ-66",
        offsetX = 6,
        offsetY = 58,
        orientation = 90,
        category = "Ground Vehicles",
      },
      [14] = {
        name = "GAZ-66",
        offsetX = 2,
        offsetY = 58,
        orientation = 90,
        category = "Ground Vehicles",
      },
      [15] = {
        name = "GAZ-66",
        offsetX = -2,
        offsetY = 58,
        orientation = 90,
        category = "Ground Vehicles",
      },
    },
  },
  [2] = {
    ["name"] = "Combine Spam",
    ["statics"] = {
      [1] = {
        name = "Tech combine",
        offsetX = 0,
        offsetY = 0,
        orientation = 0,
        category = "Fortification",
      },
      [2] = {
        name = "Tech combine",
        offsetX = -65,
        offsetY = 0,
        orientation = 0,
        category = "Fortification",
      },
      [3] = {
        name = "Tech combine",
        offsetX = -130,
        offsetY = 0,
        orientation = 0,
        category = "Fortification",
      },
      [4] = {
        name = "Tech combine",
        offsetX = 0,
        offsetY = 100,
        orientation = 180,
        category = "Fortification",
      },
      [5] = {
        name = "Tech combine",
        offsetX = -65,
        offsetY = 100,
        orientation = 180,
        category = "Fortification",
      },
      [6] = {
        name = "Tech combine",
        offsetX = -130,
        offsetY = 100,
        orientation = 180,
        category = "Fortification",
      },
      [7] = {
        name = "Tech combine",
        offsetX = 0,
        offsetY = 373,
        orientation = 0,
        category = "Fortification",
      },
      [8] = {
        name = "Tech combine",
        offsetX = -65,
        offsetY = 373,
        orientation = 0,
        category = "Fortification",
      },
      [9] = {
        name = "Tech combine",
        offsetX = -130,
        offsetY = 373,
        orientation = 0,
        category = "Fortification",
      },
      [10] = {
        name = "Tech combine",
        offsetX = 0,
        offsetY = 473,
        orientation = 180,
        category = "Fortification",
      },
      [11] = {
        name = "Tech combine",
        offsetX = -65,
        offsetY = 473,
        orientation = 180,
        category = "Fortification",
      },
      [12] = {
        name = "Tech combine",
        offsetX = -130,
        offsetY = 473,
        orientation = 180,
        category = "Fortification",
      },
      [13] = {
        name = "Tank",
        offsetX = -187,
        offsetY = -40,
        orientation = 0,
        category = "Fortification",
      },
      [14] = {
        name = "Tank",
        offsetX = -187,
        offsetY = -5,
        orientation = 0,
        category = "Fortification",
      },
      [15] = {
        name = "Tank",
        offsetX = -187,
        offsetY = 30,
        orientation = 0,
        category = "Fortification",
      },
      [16] = {
        name = "Tank",
        offsetX = -187,
        offsetY = 65,
        orientation = 0,
        category = "Fortification",
      },
      [17] = {
        name = "Tank",
        offsetX = -187,
        offsetY = 100,
        orientation = 0,
        category = "Fortification",
      },
      [18] = {
        name = "Tank",
        offsetX = -187,
        offsetY = 135,
        orientation = 0,
        category = "Fortification",
      },
      [19] = {
        name = "Tank",
        offsetX = 54,
        offsetY = 341,
        orientation = 0,
        category = "Fortification",
      },
      [20] = {
        name = "Tank",
        offsetX = 54,
        offsetY = 376,
        orientation = 0,
        category = "Fortification",
      },
      [21] = {
        name = "Tank",
        offsetX = 54,
        offsetY = 411,
        orientation = 0,
        category = "Fortification",
      },
      [22] = {
        name = "Tank",
        offsetX = 54,
        offsetY = 446,
        orientation = 0,
        category = "Fortification",
      },
      [23] = {
        name = "Tank",
        offsetX = 54,
        offsetY = 481,
        orientation = 0,
        category = "Fortification",
      },   
      [24] = {
        name = "Tank",
        offsetX = 54,
        offsetY = 516,
        orientation = 0,
        category = "Fortification",
      }, 
    },
  },
}

CSG8_TEMPLATES.samTemplates = {
  [1] = {
    ["name"] = "SA-2 SAM Site (HDS)",
    ["template"] = "HDS SAM SA-2 Battery (Russia)",
    ["statics"] = {
      [1] = {
        name = "ERO_Revetment_Platform2",
        offsetX = 0,
        offsetY = -5,
        orientation = 90,
        category = "Fortification",
      },
      [2] = {
        name = "ERO_Revetment_SAM_OC_elevated",
        offsetX = -335,
        offsetY = 481,
        orientation = 0,
        category = "Fortification",
      },
      [3] = {
        name = "ERO_Revetment_SAM_OC2_elevated",
        offsetX = -202,
        offsetY = 391,
        orientation = 56,
        category = "Fortification",
      },
      [4] = {
        name = "ERO_Revetment_SAM_OC2_elevated",
        offsetX = -202,
        offsetY = 559,
        orientation = 123,
        category = "Fortification",
      },
      [5] = {
        name = "ERO_Revetment_SAM_OC2_elevated",
        offsetX = -340,
        offsetY = 313,
        orientation = 0,
        category = "Fortification",
      },
      [6] = {
        name = "ERO_Revetment_SAM_OC2_elevated",
        offsetX = -341,
        offsetY = 641,
        orientation = 180,
        category = "Fortification",
      },
      [7] = {
        name = "ERO_Revetment_SAM_OC2_elevated",
        offsetX = -475,
        offsetY = 397,
        orientation = 300,
        category = "Fortification",
      },
      [8] = {
        name = "ERO_Revetment_SAM_OC2_elevated",
        offsetX = -476,
        offsetY = 560,
        orientation = 230,
        category = "Fortification",
      },
      [9] = {
        name = "ERO_SA2_SNR75",
        offsetX = -328,
        offsetY = 474,
        orientation = 0,
        category = "Ground Vehicles",
      },
      [10] = {
        name = "ERO_Tent_C2",
        offsetX = -71,
        offsetY = -39,
        orientation = 45,
        category = "Fortification",
      },
      [11] = {
        name = "ERO_Tent_C2",
        offsetX = -79,
        offsetY = -30,
        orientation = 45,
        category = "Fortification",
      },
      [12] = {
        name = "ERO_Revetment_SAM_O3",
        offsetX = -266,
        offsetY = 347,
        orientation = 233,
        category = "Fortification",
      },
      [13] = {
        name = "GeneratorF",
        offsetX = -270,
        offsetY = 345,
        orientation = 356,
        category = "Fortification",
      },
      [14] = {
        name = "ERO_Revetment_D",
        offsetX = -289,
        offsetY = 397,
        orientation = 220,
        category = "Fortification",
      },
      [15] = {
        name = "KAMAZ Truck",
        offsetX = -295,
        offsetY = 390,
        orientation = 179,
        category = "Fortification",
      },
      [16] = {
        name = "ERO_S75_Reload",
        offsetX = -284,
        offsetY = 395,
        orientation = 313,
        category = "Fortification",
      },
      [17] = {
        name = "ERO_Revetment_D",
        offsetX = -231,
        offsetY = 481,
        orientation = 270,
        category = "Fortification",
      },
      [18] = {
        name = "KAMAZ Truck",
        offsetX = -229,
        offsetY = 472,
        orientation = 241,
        category = "Ground Vehicles",
      },
      [19] = {
        name = "ERO_S75_Reload",
        offsetX = -227,
        offsetY = 485,
        orientation = 0,
        category = "Ground Vehicles",
      },
      [20] = {
        name = "ERO_Revetment_D",
        offsetX = -286,
        offsetY = 561,
        orientation = 324,
        category = "Ground Vehicles",
      },
      [21] = {
        name = "KAMAZ Truck",
        offsetX = -278,
        offsetY = 557,
        orientation = 270,
        category = "Ground Vehicles",
      },
      [22] = {
        name = "ERO_S75_Reload",
        offsetX = -286,
        offsetY = 567,
        orientation = 55,
        category = "Ground Vehicles",
      },
      [23] = {
        name = "ERO_Revetment_SAM_O2",
        offsetX = -256,
        offsetY = 620,
        orientation = 36,
        category = "Ground Vehicles",
      },
      [24] = {
        name = "ERO_SA2_Trailer",
        offsetX = -249,
        offsetY = 627,
        orientation = 36,
        category = "Ground Vehicles",
      },
      [25] = {
        name = "ERO_Revetment_D",
        offsetX = -396,
        offsetY = 559,
        orientation = 39,
        category = "Ground Vehicles",
      },
      [26] = {
        name = "KAMAZ Truck",
        offsetX = -402,
        offsetY = 558,
        orientation = 270,
        category = "Ground Vehicles",
      },
      [27] = {
        name = "ERO_S75_Reload",
        offsetX = -395,
        offsetY = 568,
        orientation = 311,
        category = "Ground Vehicles",
      },
      [28] = {
        name = "ERO_Revetment_D",
        offsetX = -430,
        offsetY = 477,
        orientation = 89,
        category = "Ground Vehicles",
      },
      [29] = {
        name = "KAMAZ Truck",
        offsetX = -433,
        offsetY = 473,
        orientation = 309,
        category = "Ground Vehicles",
      },
      [30] = {
        name = "ERO_S75_Reload",
        offsetX = -436,
        offsetY = 485,
        orientation = 0,
        category = "Ground Vehicles",
      },
      [31] = {
        name = "ERO_Revetment_D",
        offsetX = -383,
        offsetY = 394,
        orientation = 145,
        category = "Ground Vehicles",
      },
      [32] = {
        name = "KAMAZ Truck",
        offsetX = -392,
        offsetY = 398,
        orientation = 101,
        category = "Ground Vehicles",
      },
      [33] = {
        name = "ERO_S75_Reload",
        offsetX = -384,
        offsetY = 388,
        orientation = 235,
        category = "Ground Vehicles",
      },
      [34] = {
        name = "ERO_Tent_A",
        offsetX = -421,
        offsetY = 344,
        orientation = 45,
        category = "Ground Vehicles",
      },
      [35] = {
        name = "ERO_Tent_A",
        offsetX = -429,
        offsetY = 352,
        orientation = 45,
        category = "Ground Vehicles",
      },
    },
  },
  [2] = {
    ["name"] = "SA-2 SAM Site MAD (HDS)",
    ["template"] = "HDS SAM SA-2 Battery MAD (Russia)",
    ["statics"] = {
      [1] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = -1,
        offsetY = 2,
        orientation = 164,
        category = "Fortification",
      },
      [2] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = 21,
        offsetY = 17,
        orientation = 129,
        category = "Fortification",
      },
      [3] = {
        name = "ERO_SA2_Trailer",
        offsetX = 21,
        offsetY = 14,
        orientation = 218,
        category = "Ground Vehicles",
      },
      [4] = {
        name = "ERO_Revetment_SAM_O3",
        offsetX = 120,
        offsetY = -88,
        orientation = 29,
        category = "Fortification",
      },
      [5] = {
        name = "ERO_S75_Reload",
        offsetX = 137,
        offsetY = -134,
        orientation = 43,
        category = "Fortification",
      },
      [6] = {
        name = "ERO_Revetment_D",
        offsetX = 147,
        offsetY = -138,
        orientation = 132,
        category = "Fortification",
      },
      [7] = {
        name = "ERO_Revetment_SAM_O3",
        offsetX = 190,
        offsetY = -160,
        orientation = 62,
        category = "Fortification",
      },
      [8] = {
        name = "ERO_Revetment_SAM_O3",
        offsetX = 282,
        offsetY = -133,
        orientation = 134,
        category = "Fortification",
      },
      [9] = {
        name = "ERO_S75_Reload",
        offsetX = 312,
        offsetY = -93,
        orientation = 161,
        category = "Fortification",
      },
      [10] = {
        name = "ERO_Revetment_D",
        offsetX = 312,
        offsetY = -82,
        orientation = 254,
        category = "Fortification",
      },
      [11] = {
        name = "ERO_Revetment_SAM_O3",
        offsetX = 309,
        offsetY = -34,
        orientation = 190,
        category = "Fortification",
      },
      [12] = {
        name = "ERO_Revetment_SAM_O3",
        offsetX = 245,
        offsetY = 41,
        orientation = 254,
        category = "Fortification",
      },
      [13] = {
        name = "ERO_S75_Reload",
        offsetX = 193,
        offsetY = 54,
        orientation = 281,
        category = "Fortification",
      },
      [14] = {
        name = "ERO_Revetment_D",
        offsetX = 186,
        offsetY = 47,
        orientation = 12,
        category = "Fortification",
      },
      [15] = {
        name = "ERO_Revetment_SAM_O3",
        offsetX = 146,
        offsetY = 18,
        orientation = 304,
        category = "Fortification",
      },
      [16] = {
        name = "ERO_Revetment_SAM_OC2_elevated",
        offsetX = 217,
        offsetY = -57,
        orientation = 251,
        category = "Fortification",
      },
      [17] = {
        name = "ERO_SA2_SNR75",
        offsetX = 231,
        offsetY = -58,
        orientation = 355,
        category = "Ground Vehicles",
      },
      [18] = {
        name = "ERO_5S99_Trailer",
        offsetX = 244,
        offsetY = -62,
        orientation = 0,
        category = "Ground Vehicles",
      },
    },
  },
  [3] = {
    ["name"] = "SA-3 SAM Site MAD (HDS)",
    ["template"] = "HDS SAM SA-2 Battery MAD (Russia)",
    ["statics"] = {
      [1] = {
        name = "ERO_Revetment_SAM_OC_elevated",
        offsetX = -4,
        offsetY = -1,
        orientation = 197,
        category = "Fortification",
      },
      [2] = {
        name = "ERO_Revetment_SAM11",
        offsetX = -93,
        offsetY = -77,
        orientation = 196,
        category = "Fortification",
      },
      [3] = {
        name = "ERO_Revetment_SAM_UC",
        offsetX = -165,
        offsetY = -23,
        orientation = 176,
        category = "Fortification",
      },
      [4] = {
        name = "ERO_Revetment_SAM_UC",
        offsetX = -200,
        offsetY = -77,
        orientation = 196,
        category = "Fortification",
      },
      [5] = {
        name = "ERO_Revetment_SAM_UC",
        offsetX = -183,
        offsetY = -136,
        orientation = 196,
        category = "Fortification",
      },
      [6] = {
        name = "ERO_Revetment_SAM_UC",
        offsetX = -129,
        offsetY = -167,
        orientation = 225,
        category = "Fortification",
      },
    },
  },
}

CSG8_TEMPLATES.aaaTemplates = {
  [1] = {
    ["name"] = "Basic 6-point AAA Battery",
    ["template"] = "Basic 6-point AAA Battery",
    ["statics"] = {
      [1] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = 29,
        offsetY = -48,
        orientation = 303,
        category = "Fortification",
      },
      [2] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = 59,
        offsetY = -1,
        orientation = 0,
        category = "Fortification",
      },
      [3] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = 33,
        offsetY = 51,
        orientation = 57,
        category = "Fortification",
      },
      [4] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = -33,
        offsetY = 51,
        orientation = 128,
        category = "Fortification",
      },
      [5] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = -59,
        offsetY = 0,
        orientation = 180,
        category = "Fortification",
      },
      [6] = {
        name = "ERO_Revetment_Tank_U",
        offsetX = -30,
        offsetY = -46,
        orientation = 234,
        category = "Fortification",
      },
      [7] = {
        name = "ERO_Revetment_SAM_O2",
        offsetX = -1,
        offsetY = 6,
        orientation = 180,
        category = "Fortification",
      },
    },
  },
}
env.info( "*** CSG8 *** TEMPLATES 01.004 Script Loaded Successfully" )